### PR TITLE
Fix checkbox & radio input elements

### PR DESCRIPTION
**Pull request by ZsharE**
**Bugs found:**

- nested `<label>` tags
- duplicate id attribute for each control
- missing control classes: `d-block`, `my-2`
- adding events on labels
- text label missing

### CODE REVIEW

**Comment by zoephilipps** [comment]
@hisk this looks pretty legit, when are you planning on testing/merging?

**Comment by tstojecki** [comment]
This is a bug indeed, thanks @ZsharE

**Comment by zoephilipps** [comment]
@hisk bump. We bought everything from Shards, which is supposed to include support. I reached out via support ticket to see if you could merge this PR. Any thoughts?

**Comment by zoephilipps** [comment]
Thanks for merging, @hisk!

**Pull request merged**
